### ISSUE TITLE
Links in rendered notebooks

### ISSUE THREAD

**Issue by kadrlica** [NOAO/nat-nb#1]
Thanks for some great example notebooks. 

I've noticed that the url links in the GitHub rendered versions of the notebooks are not redirecting me correctly. Should I be looking at a different "official" rendered version of these notebooks?

For example, the link for "Details" at the top of [api-authentication.ipynb](https://github.com/NOAO/nat-nb/blob/master/api-authentication.ipynb) is trying to send me to:

https://render.githubusercontent.com/view/ipynb?commit=0529acb281a64dccf35b36140a21139542000bac&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4e4f414f2f6e61742d6e622f303532396163623238316136346463636633356233363134306132313133393534323030306261632f6170692d61757468656e7469636174696f6e2e6970796e62&nwo=NOAO%2Fnat-nb&path=api-authentication.ipynb&repository_id=236548929&repository_type=Repository#details

**Comment by pothiers** [comment]
GitHub does its own rendering of notebooks.  While it is generally pretty good for seeing what is the notebook, its not meant for executing things.  You can copy the notebook to your own machine and run under Jupyter Notebook locally.  But for that specific case if you use the github "raw" button you can see that the "Detail" link simply jumps to the "details" section in the notebook.
